name: zest_client
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.1.1
  provider: ^6.0.0
  table_calendar: ^3.0.9
  intl: ^0.20.2
  html: ^0.15.0
  ai_barcode_scanner: 7.1.0
  flutter_dotenv: ^5.1.0
  nfc_host_card_emulation: 1.1.0
  qr_flutter: ^4.1.0
  cupertino_icons: ^1.0.8
  http: ^1.5.0
  percent_indicator: ^4.2.5
  flutter_localizations:
    sdk: flutter
  flutter_nfc_kit: ^3.4.2
  flutter_ble_peripheral: ^2.1.0
  flutter_blue_plus: ^1.31.17
  permission_handler: ^11.3.0
  flutter_hooks: ^0.21.3+1
  hooks_riverpod: ^3.0.0
  riverpod_annotation:
  functional_widget_annotation:
  flutter_query: ^0.6.0
  terminate_restart: ^1.0.11

dev_dependencies:
  flutter_launcher_icons: ^0.14.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^3.0.0
  riverpod_lint:
  functional_widget:
  build_runner:

dependency_overrides:
  functional_widget:
    git:
      url: https://github.com/sitespectrum/flutter_functional_widget
      ref: 8afc7c3
      path: packages/functional_widget
  functional_widget_annotation:
    git:
      url: https://github.com/sitespectrum/flutter_functional_widget
      ref: 8afc7c3
      path: packages/functional_widget_annotation

  build_runner_core:
    git:
      url: https://github.com/sitespectrum/dart_build_with_errors
      ref: allow_errors_4.0.0
      path: build_runner_core

flutter:
  uses-material-design: true

  assets:
    - assets/icon/Zest_logo.png

  shaders:
    - assets/shaders/topo.frag

  fonts:
    - family: Geist
      fonts:
        - asset: assets/fonts/Geist-VariableFont_wght.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "./assets/icon/Zest_logo.png"
  min_sdk_android: 21
