import 'package:flutter/material.dart';
import 'dart:ui' as ui;
import 'package:shared_preferences/shared_preferences.dart';

class LanguageProvider with ChangeNotifier {
  Locale _currentLocale = const Locale('hu');

  Locale get currentLocale => _currentLocale;
  String get languageCode => _currentLocale.languageCode;

  LanguageProvider() {
    _loadLanguage();
  }

  Future<void> changeLanguage(String languageCode) async {
    _currentLocale = Locale(languageCode);
    notifyListeners();

    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('selected_language', languageCode);
  }

  Future<void> _loadLanguage() async {
    final prefs = await SharedPreferences.getInstance();
    final savedLang = prefs.getString('selected_language');
    if (savedLang != null) {
      _currentLocale = Locale(savedLang);
    } else {
      final systemLocale = const Locale('hu');
      if (systemLocale.languageCode == 'hu') {
        _currentLocale = const Locale('hu');
      } else {
        _currentLocale = const Locale('en');
      }
    }
    notifyListeners();
  }

  String getText(String key) {
    return _localizedValues[languageCode]?[key] ?? key;
  }

  static final Map<String, Map<String, String>> _localizedValues = {
    'hu': {
      'register_button_main': 'Regisztráció',
      'login_button_main': 'Már van fiókod',
      'username_hint': 'Felhasználónév',
      'email_hint': 'Email',
      'password_hint': 'Jelszó',
      'continue_register': 'Regisztráció folytatása',
      'my_details': 'Adataim',
      'height': 'Magasság',
      'weight': 'Súly',
      'born_in': 'Szül. idő',
      'gender': 'Nem',
      'male': 'Férfi',
      'female': 'Nő',
      'goals': 'Célok',
      'bulking': 'Tömegelés',
      'level_maintenance': 'Szintentartás',
      'weight_loss': 'Fogyás',
      'activity': 'Aktivitás',
      'slightly_active': 'Enyhén aktív',
      'slightly_active_desc': 'Napi séta, heti 1-3 könnyű edzés.',
      'moderately_active': 'Közepesen aktív',
      'moderately_active_desc': 'Heti 3-5 edzés, ülőmunka.',
      'very_active': 'Nagyon aktív',
      'very_active_desc': 'Napi edzés, fizikai munka.',
      'extremely_active': 'Extrém aktív',
      'extremely_active_desc': 'Napi 2 edzés, például sportkarrier.',
      'finish_register': 'Regisztráció befejezése',
      'username_and_email_hint': 'Felhasználónév / Email',
      'login': 'Bejelentkezés',
      'home_page': 'Főoldal',
      'calorie_deficit': 'Kalóriadeficit',
      'recent_workout': 'Legutóbbi edzés',
      'recent_meal': 'Legutóbbi étkezés',
      'workout_page': 'Edzés',
      'previous_workouts': 'Korábbi edzések',
      'previous_meals': 'Korábbi étkezések',
      'my_templates': 'Sablonjaim',
      'health_page': 'Egészség',
      'nutrients_consumed': 'Bevitt tápanyagok',
      'protein': 'Fehérje',
      'carbs': 'Szénhidrát',
      'fat': 'Zsír',
      'profile_page': 'Profil',
      'personal_details': 'Személyes adatok',
      'user': 'Felhasználó',
      'calories': 'Kalória',
      'daily_goals': 'Napi célok',
      'modify_details': 'Adatok módosítása',
      'logout': 'Kijelentkezés',
      'language': 'Nyelv',
      'new_password': 'Új jelszó',
      'save_changes': 'Módosítások mentése',
      'no_data_on_this_day': 'Ezen a napon nincs adat',
      'close': 'Bezárás',
      'add_new_meal': 'Új étkezés hozzáadása',
      'new_meal': 'Új étkezés',
      'breakfast': 'Reggeli',
      'lunch': 'Ebéd',
      'dinner': 'Vacsora',
      'other': 'Egyéb',
      'no_added_meal_yet': 'Nincsenek hozzáadott ételek',
      'summary': 'Összegzés',
      'add': 'Hozzáadás',
      'continue': 'Tovább',
      'save_sample': 'Sablon mentése',
      'sample_name': 'Sablon neve',
      'save_without_sample': 'Nincs mentés',
      'save': 'Mentés',
      'search_hint': 'Keresés',
      'choose_quantity': 'válassz mennyiséget!',
      'save_as_meal': 'Mentés étkezésként',
      'edit': 'Szerkesztés',
      'continue_meal': 'Folytatás',
      'create_new': 'Új létrehozása',
      'new_workout': 'Új edzés',
      'no_added_exercise_yet': 'Nincsenek hozzáadott gyakorlatok',
      'no_added_template_yet': 'Nincsenek hozzáadott sablonok',
      'start': 'Kezdés',
      'delete': 'Törlés',
      'unknown_template': 'Ismeretlen sablon',
      'piece(s)': 'Darab',
      'portion': 'Adag',
      'description': 'Leírás',
      'category': 'Kategória',
      'equipment': 'Felszerelés',
      'force': 'Típus',
      'mechanic': 'Mechanic',
      'level': 'Szint',
      'primary_muscles': 'Elsődleges izomcsoport',
      'cancel': 'Mégse',
      'loading': 'Betöltés',
      'exercise': 'Gyakorlat',
      'set(s)': 'gyakorlat(ok)',
      'data_successfully_updated': 'Adatok sikeresen frissítve!',
      'choose_date_of_birth': 'Válassz születési dátumot!',
      'all_fields_are_required': 'Tölts ki minden mezőt!',
      'loaded': 'betöltve!',
      'meal_deleted': 'Étel törölve.',
      'deletion_failed': 'Sikertelen törlés.',
      'saved_successfully': 'Sikeres mentés!',
      'added_to_list': 'hozzáadva a listához!',
      'no_barcode_found': 'Nem található vonalkód!',
      'no_unit_found': 'Nem található mértékegység ehhez az ételhez.',
      'no_userId_found': 'Nem található userId.',
      'no_meals_selected': 'Nincs étel kiválasztva.',
      'failed_to_fetch_meals': 'Nem sikerült lekérni az étkezéseket.',
      'failed_to_save': 'Nem sikerült menteni',
      'morning': 'reggeli edzés',
      'afternoon': 'délutáni edzés',
      'evening': 'esti edzés',
      'night': 'éjszakai edzés',
      'finish_workout': 'Edzés befejezése',
      'set': 'Soroz.',
      'reps': 'Ismétlések',
      'done': 'Kész',
      'add_set': 'Hozzáadás',
      'remove': 'Eltávolítás',
      'continue_workout': 'Folytatás',
      'name_the_template': 'Adj nevet a sablonnak!',
      'min': 'perc',
      'sets': 'Sorozatok',
      'exercises': 'Gyakorlatok',
      'volume': 'Összesen',
      'duration': 'Időtartam',
      'workout': 'Edzés',
      'duplicate_template': 'Ez a sablon név már létezik!',
      "sure_delete_template": "Biztosan törölni szeretnéd ezt a sablont:",
      "deleted_successfully": "Sikeresen törölve!",
      'save_as_workout': 'Mentés edzésként',
      'load_template': 'Sablon betöltése',
      'add_new_workout': 'Új edzés hozzáadása',
      'share': 'Megosztás',
      'share_via_NFC': 'Megosztás NFC-n keresztül',
      'recive_workout': 'Edzés fogadása',
      'or': 'Vagy',
      'scan': 'QR kód belolvasása',
      'no_qr_code_yet': 'Még nincs QR kód',
      'no_added_workout_yet': 'Nincsenek hozzáadott edzések',
      'distance': 'Távolság',
      'time': 'Idő',
      'unknown_exercise': 'Ismeretlen gyakorlat',
      "friends_title": "Barátok",
      "my_friends": "Saját barátok",
      "requests": "Kérések",
      "search": "Keresés",
      "no_friends_yet": "Még nincsenek barátaid.",
      "no_pending_requests": "Nincs függőben lévő kérés.",
      "friend_request_subtitle": "Barátnak jelölt téged",
      "search_username_hint": "Felhasználónév keresése...",
      "send_request": "Jelölés",
      "request_sent": "Jelölés elküldve!",
      "friend_added": "Barát hozzáadva!",
      "request_declined": "Elutasítva.",
      "error_occurred": "Hiba történt",
      "friend_deleted_successfully": "Barát sikeresen törölve",
      'delete_friend_title': 'Barát törlése',
      'sure_delete_friend': 'Biztosan törölni szeretnéd ezt a barátot:',
      "friend_profile": "Barát profilja",
      "workout_templates": "Edzés sablonok",
      "meal_templates": "Étkezés sablonok",
      "no_public_workouts": "Nincsenek publikus edzés sablonok",
      "no_public_meals": "Nincsenek publikus étkezés sablonok",
      "save_to_my_templates": "Mentés saját sablonok közé",
      "workout_saved": "Edzés sablon sikeresen elmentve!",
      "meal_saved": "Étkezés sablon sikeresen elmentve!",
      "anonymous_workout": "Névtelen edzés",
      "anonymous_meal": "Névtelen étkezés",
      "exercises_count": "gyakorlat",
      "minutes": "perc",
      "ingredients_count": "összetevő",
      'burnt_calories': 'Elégetett kalóriák',
      'create_exercise': 'Gyak. létrehozása',
      'name': 'Név',
      'primaryMuscle': 'Fő izom',
      'secondaryMuscle': 'Másodl. izom',
      'select': 'kiválasztása',
      'read': 'Olvasás',
      'recent_exercises': 'Korábbi gyakorlatok',
      'exercise_added_to_list': 'gyakorlat hozzáadva a listához!',
      'meal_added_to_list': 'étkezés hozzáadva a listához!',
      'qr_success': 'QR kód legenerálva!',
      'error': 'Hiba',
      'missing_bt': 'Hiányzó bluetooth engedélyek',
      'failed_to_identitify': 'Nem sikerült azonosítani az eszközt',
      'start_sharing': 'Megosztás indítása',
      'nfc_&_bt_active': 'NFC és Bluetooth aktív',
      'loading_workout': 'Loading workout',
      'touch_the_other_phone': 'Érintsd a másik telefonhoz',
      'decoding_error': 'Dekódolási hiba',
      'missing_error': 'Nem található vagy lejárt megosztás',
      'template_loaded': 'Sablon betöltve!',
      'no_history': 'Nincsenek előzmények',
    },
    'en': {
      'register_button_main': "Register",
      'login_button_main': 'Already have an account',
      'username_hint': 'Username',
      'email_hint': 'Email',
      'password_hint': 'Password',
      'continue_register': 'Continue registration',
      'my_details': 'My details',
      'height': 'Height',
      'weight': 'Weight',
      'born_in': 'Date of birth',
      'gender': 'Gender',
      'male': 'Male',
      'female': 'Female',
      'goals': 'Goals',
      'bulking': 'Bulking',
      'level_maintenance': 'Level maintenance',
      'weight_loss': 'Weight loss',
      'activity': 'Activity',
      'slightly_active': 'Slightly active',
      'slightly_active_desc': 'Daily walking, 1-3 light workout per week.',
      'moderately_active': 'Moderately active',
      'moderately_active_desc': '3-5 workout per week, sedentary work.',
      'very_active': 'Very active',
      'very_active_desc': 'Daily workout, physical work.',
      'extremely_active': 'Extremely active',
      'extremely_active_desc': '2 daily workouts, e.g. sports career.',
      'finish_register': 'Finish registration',
      'username_and_email_hint': 'Username / Email',
      'login': 'Login',
      'home_page': 'Home',
      'calorie_deficit': 'Calorie deficit',
      'recent_workout': 'Recent workout',
      'recent_meal': 'Recent meal',
      'workout_page': 'Workout',
      'previous_workouts': 'Previous workouts',
      'previous_meals': 'Previous meals',
      'my_templates': 'My templates',
      'health_page': 'Health',
      'nutrients_consumed': 'Nutrients consumed',
      'protein': 'Protein',
      'carbs': 'Carbonhidrates',
      'fat': 'Fat',
      'profile_page': 'Profile',
      'personal_details': 'Personal details',
      'user': 'User',
      'calories': 'Calories',
      'daily_goals': 'Daily goals',
      'modify_details': 'Modify details',
      'logout': 'Logout',
      'language': 'Language',
      'new_password': 'New password',
      'save_changes': 'Save changes',
      'no_data_on_this_day': 'No data on this day',
      'close': 'Close',
      'add_new_meal': 'Add new meal',
      'new_meal': 'New meal',
      'breakfast': 'Breakfast',
      'lunch': 'Lunch',
      'dinner': 'Dinner',
      'other': 'Other',
      'no_added_meal_yet': 'No added meal yet',
      'summary': 'Summary',
      'add': 'Add',
      'continue': 'Continue',
      'save_sample': 'Save sample',
      'sample_name': 'Sample name',
      'save_without_sample': 'No save',
      'save': 'Save',
      'search_hint': 'Search',
      'choose_quantity': 'Choose quantity!',
      'save_as_meal': 'Save as meal',
      'edit': 'Edit',
      'continue_meal': 'Continue',
      'create_new': 'Create new',
      'new_workout': 'New workout',
      'no_added_exercise_yet': 'No added exercise yet',
      'no_added_template_yet': 'No added template yet',
      'start': 'Start',
      'delete': 'Delete',
      'unknown_template': 'Unknown template',
      'piece(s)': 'piece(s)',
      'portion': 'Portion',
      'description': 'Description',
      'category': 'Category',
      'equipment': 'Equipment',
      'force': 'Force',
      'mechanic': 'Mechanic',
      'level': 'Level',
      'primary_muscles': 'Primary muscle',
      'cancel': 'Cancel',
      'loading': 'Loading',
      'exercise': 'Exercise',
      'set(s)': 'set(s)',
      'data_successfully_updated': 'Data successfully updated!',
      'choose_date_of_birth': 'Choose date of birth!',
      'all_fields_are_required': 'All fields are required',
      'loaded': 'loaded!',
      'meal_deleted': 'Meal deleted.',
      'deletion_failed': 'Deletion failed',
      'saved_successfully': 'Saved successfully!',
      'added_to_list': 'added to list!',
      'no_barcode_found': 'No barcode found.',
      'no_unit_found': 'No unit found for this meal.',
      'no_userId_found': 'No userId found',
      'no_meals_selected': 'No meals selected.',
      'failed_to_fetch_meals': 'Failed to fetch meals.',
      'failed_to_save': 'Failed to save',
      'morning': 'morning workout',
      'afternoon': 'afternoon workout',
      'evening': 'evening workout',
      'night': 'night workout',
      'finish_workout': 'Finish workout',
      'set': 'Set',
      'reps': 'Reps',
      'done': 'Done',
      'add_set': 'Add set',
      'remove': 'Remove',
      'continue_workout': 'Continue',
      'name_the_template': 'Name the template!',
      'min': 'min',
      'sets': 'Sets',
      'exercises': 'Exercises',
      'volume': 'Volume',
      'duration': 'Duration',
      'workout': 'Workout',
      'duplicate_template': 'This template name already exists!',
      "sure_delete_template": "Are you sure you want to delete this template:",
      "deleted_successfully": "Deleted successfully!",
      'save_as_workout': 'Save as workout',
      'load_template': 'Load template',
      'add_new_workout': 'Add new workout',
      'share': 'Share',
      'share_via_NFC': 'Share via NFC',
      'recive_workout': 'Recive workout',
      'or': 'Or',
      'scan': 'Scan QR code',
      'no_qr_code_yet': 'No QR code yet',
      'no_addded_workout_yet': 'No added workout yet',
      'distance': 'Distance',
      'time': 'Time',
      'unknown_exercise': 'Unknown exercise',
      "friends_title": "Friends",
      "my_friends": "My Friends",
      "requests": "Requests",
      "search": "Search",
      "no_friends_yet": "No friends yet.",
      "no_pending_requests": "No pending requests.",
      "friend_request_subtitle": "Sent you a friend request",
      "search_username_hint": "Search username...",
      "send_request": "Request",
      "request_sent": "Request sent!",
      "friend_added": "Friend added!",
      "request_declined": "Declined.",
      "error_occurred": "An error occurred",
      'friend_deleted_successfully': 'Friend removed successfully!',
      'delete_friend_title': 'Remove Friend',
      'sure_delete_friend': 'Are you sure you want to remove:',
      "friend_profile": "Friend Profile",
      "workout_templates": "Workout Templates",
      "meal_templates": "Meal Templates",
      "no_public_workouts": "No public workout templates",
      "no_public_meals": "No public meal templates",
      "save_to_my_templates": "Save to my templates",
      "workout_saved": "Workout template saved successfully!",
      "meal_saved": "Meal template saved successfully!",
      "anonymous_workout": "Unnamed workout",
      "anonymous_meal": "Unnamed meal",
      "exercises_count": "exercises",
      "minutes": "min",
      "ingredients_count": "ingredients",
      'burnt_calories': 'Burnt calories',
      'create_exercise': 'Create exercise',
      'name': 'Name',
      'primaryMuscle': 'Primary muscle',
      'secondaryMuscle': 'Sec. muscle',
      'select': 'select',
      'read': 'Read',
      'recent_exercises': 'Recent exercises',
      'exercise_added_to_list': 'exercise(s) added to list!',
      'meal_added_to_list': 'meal(s) added to list!',
      'qr_success': 'QR code generated!',
      'error': 'Error',
      'missing_bt': 'Missing bluetooth permissions',
      'failed_to_identitify': 'Failed to identitify the device',
      'start_sharing': 'Start sharing',
      'touch_the_other_phone': 'Touch the other phone',
      'reciveing': 'Reciveing through Bluetooth',
      'decoding_error': 'Decoding error',
      'missing_error': 'Share missing or not found',
      'template_loaded': 'Template loaded!',
      'no_history': 'No history',
    },
  };
}
