services:
  zest-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zest-server
    ports:
      - "10000:10000"
    volumes:
      - ./db:/app/db
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:10000
    restart: unless-stopped
    command: dotnet ef database update && dotnet server.dll
