services:
  zest-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zest-server
    ports:
      - "10000:10000"
    volumes:
      - ./zest.db:/app/zest.db
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:10000
    restart: unless-stopped
